name: Node.js Deployment with Docker

on:
  push:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: DOCKER_USERNAME/greenie:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to Qnap NAS
        uses: appleboy/ssh-action@v0.4.2
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            docker pull DOCKER_USERNAME/greenie:latest
            docker stop greenie || true
            docker rm greenie || true
            docker run -d --name greenie -p 3000:3000 DOCKER_USERNAME/greenie:latest
