name: Node.js Deployment with Docker

on:
  push:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/greenie

      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          dockerfile: ./Dockerfile

      - name: Deploy to Qnap NAS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker pull ${{ secrets.NAS_USERNAME }}/greenie:latest
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker stop greenie || true
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker rm greenie || true
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker run -d --name greenie -p 3000:3000 ${{ secrets.NAS_USERNAME }}/greenie:latest
